// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASs38CNAJ6RKISpYZWmM4ED9umMra6Axs',
    appId: '1:342360206547:web:c7a726efb4993188afb826',
    messagingSenderId: '342360206547',
    projectId: 'misionkids',
    authDomain: 'misionkids.firebaseapp.com',
    storageBucket: 'misionkids.firebasestorage.app',
    measurementId: 'G-DVWD8C2S0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu1JTmimFV-uLcwjL7XRmyGWcG1v4gnsY',
    appId: '1:342360206547:android:c8c10692fb51971bafb826',
    messagingSenderId: '342360206547',
    projectId: 'misionkids',
    storageBucket: 'misionkids.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu1JTmimFV-uLcwjL7XRmyGWcG1v4gnsY',
    appId: '1:342360206547:ios:491d900693f1cc35afb826',
    messagingSenderId: '342360206547',
    projectId: 'misionkids',
    storageBucket: 'misionkids.firebasestorage.app',
    iosBundleId: 'com.example.josueTareas',
  );
}
